In [1]:
import random
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
vector = np.array([
  [random.uniform(0, 1)] for i in range(0, 10)
])

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35],
])

vector, matrix

(array([[0.71649461],
        [0.73678195],
        [0.75388226],
        [0.58762561],
        [0.41664167],
        [0.76766471],
        [0.66458334],
        [0.50711211],
        [0.15645211],
        [0.7585515 ]]),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [3]:
np.round(vector + 10, decimals=2)

array([[10.72],
       [10.74],
       [10.75],
       [10.59],
       [10.42],
       [10.77],
       [10.66],
       [10.51],
       [10.16],
       [10.76]])

In [4]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [5]:
vector2 = vector ** 2


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [6]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [7]:
result_matrix = np.dot(B, A)
print(result_matrix)

result_C = np.dot(result_matrix, C)
print(result_C)

result_D = np.dot(result_matrix, D)
print(result_D)

[[0.7281 0.5202]
 [0.2034 0.2846]]
[[0.5202]
 [0.2846]]
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [19]:
transposed_matrix = result_matrix.T

print("Оригінальна матриця result_matrix:")
print(result_matrix)
print("Транспонована result_matrix:")
print(transposed_matrix)
print("Форма (shape):", transposed_matrix.shape)

Оригінальна матриця result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]
Транспонована result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]
Форма (shape): (2, 2)


In [21]:
transposed_vector = vector.T

print("Оригінальний vector:")
print(vector)
print("Транспонований vector:")
print(transposed_vector)
print("Форма (shape) до:", vector.shape)
print("Форма (shape) після:", transposed_vector.shape)

Оригінальний vector:
[[0.71649461]
 [0.73678195]
 [0.75388226]
 [0.58762561]
 [0.41664167]
 [0.76766471]
 [0.66458334]
 [0.50711211]
 [0.15645211]
 [0.7585515 ]]
Транспонований vector:
[[0.71649461 0.73678195 0.75388226 0.58762561 0.41664167 0.76766471
  0.66458334 0.50711211 0.15645211 0.7585515 ]]
Форма (shape) до: (10, 1)
Форма (shape) після: (1, 10)


In [12]:
vector.T

array([[0.71649461, 0.73678195, 0.75388226, 0.58762561, 0.41664167,
        0.76766471, 0.66458334, 0.50711211, 0.15645211, 0.7585515 ]])

In [23]:
column_vector = np.expand_dims(vector, axis=1)

print("column_vector:")
print(column_vector)
print("Форма column_vector:", column_vector.shape)

column_vector:
[[[0.71649461]]

 [[0.73678195]]

 [[0.75388226]]

 [[0.58762561]]

 [[0.41664167]]

 [[0.76766471]]

 [[0.66458334]]

 [[0.50711211]]

 [[0.15645211]]

 [[0.7585515 ]]]
Форма column_vector: (10, 1, 1)


In [24]:
transposed_column_vector = column_vector.T

print("Транспонований column_vector:")
print(transposed_column_vector)
print("Форма (shape):", transposed_column_vector.shape)

Транспонований column_vector:
[[[0.71649461 0.73678195 0.75388226 0.58762561 0.41664167 0.76766471
   0.66458334 0.50711211 0.15645211 0.7585515 ]]]
Форма (shape): (1, 1, 10)
